Reduce test warnings
poliastro/poliastro pull request #1092
Opened 2021-01-27 14:49 UTC by Yash-10

In reference to #1074, this PR aims to reduce test warnings. Some warnings might need further treatment to mitigate/suppress them but this implementation fixes some of the obvious ones.

Thanks!

2021-01-27 18:51 UTC, Yash-10 commented
I am sorry for a bunch of small pushes..

2021-01-28 12:06 UTC, astrojuanlu commented on tests/tests_plotting/test_static.py
> +    op.plot_body_orbit(Mars, Time(J2000, scale="tdb"), label="Mars")
Let's use `J2000_TDB` instead https://github.com/poliastro/poliastro/blob/a43006b0cf6b9671128ff4e4ed82f45bea6d5205/src/poliastro/constants/general.py#L104-L106

2021-01-28 12:13 UTC, astrojuanlu requested changes
Thanks a lot @Yash-10 ! This is on the right path. Some fixes are good as they are and I didn't say anything, for some others I left a few comments.

2021-01-28 12:13 UTC, astrojuanlu commented on tests/tests_plotting/test_static.py
> +    op.plot_body_orbit(Mars, Time(J2000, scale="tdb"), label="Mars")
Let's use `J2000_TDB` instead https://github.com/poliastro/poliastro/blob/a43006b0cf6b9671128ff4e4ed82f45bea6d5205/src/poliastro/constants/general.py#L104-L106

2021-01-28 12:13 UTC, astrojuanlu commented on tests/tests_twobody/test_orbit.py
> +    ss = Orbit.from_ephem(Sun, ephem, epoch)
The tests of `Orbit.from_body_ephem` require further discussion.

If we are still using it internally, even if it's deprecated, it should be tested. And if it has to be tested, then we should silence the deprecation warnings.

But if we are not using it internally anymore, then this approach is on the right path, but I would try not to call `Ephem.from_body` (and use a custom, dummy `Ephem`).

2021-01-28 12:13 UTC, astrojuanlu commented on tests/tests_twobody/test_orbit.py
> +@pytest.mark.filterwarnings("ignore::poliastro.twobody.orbit.PatchedConicsWarning")
Instead of filtering the warning, should we assert that it's emitted?

2021-01-28 14:44 UTC, astrojuanlu approved these changes
Looks good to me!

2021-01-28 14:52 UTC, astrojuanlu commented
As you say, there are still some warnings left but this is strictly better than before. Thanks a lot!

2021-01-28 14:52 UTC, merged

2021-01-28 14:58 UTC, Yash-10 commented
Thanks @astrojuanlu! Yes, those warnings which include `ERFA`, `Orbit.pqw` would need further treatment but can be dealt in the future too!

Thanks!!