[Continued] Implemented Jacchia77 atmospheric model
poliastro/poliastro pull request #1113
Opened 2021-03-06 10:13 UTC by DhruvSondhi

Hello, 
This PR aims to continue the effort made to implement Jacchia77 atmospheric model (Thanks to @iamabhishek0 for the work)
Cheers :)

2021-03-20 20:45 UTC, astrojuanlu requested changes
Thanks a lot for bringing this back to life @DhruvSondhi ! Please address the review comments that @jorgepiloto did on #944 and I think we are ready to go

2021-03-20 20:46 UTC, astrojuanlu commented
Also, this will need a rebase

2021-03-20 23:13 UTC, DhruvSondhi commented
Hello @astrojuanlu, I have done the requested changes 😄 ... Though we need to implement the `variation due to geomagnetic activity` & `diurnal variations in the atmosphere density` ... We can merge this into the library but there are some changes that need to be done like the Density computation here has a very weird unit & we need to address it ... I have found much legible material for implementation but I need some confirmation about the same ... So, Yes we have some work to do 😃

2021-03-20 23:32 UTC, DhruvSondhi reviewed
Checking for a bug

2021-03-20 23:32 UTC, DhruvSondhi commented on tests/tests_atmosphere/test_jacchia77.py
> +    )
@astrojuanlu Check this out ... I tried fixing this but got confused ... Will need to spend some time checking where the implementation has gone wrong as these are clearly not the units for `Density` 😞

2021-03-29 06:37 UTC, DhruvSondhi commented
@jorgepiloto Can you check the implementation? I have made the requested changes but need to discuss the implementation as it seems to be specific implementation than a more general one (Though I am not sure about it 🤔 )

2021-04-03 17:00 UTC, astrojuanlu approved these changes
This is good enough to be merged, and we can address any bugs or concerns afterwards 👍🏽 Thanks a lot @DhruvSondhi!

2021-04-03 17:00 UTC, merged

2021-04-03 17:02 UTC, DhruvSondhi commented
Sure, Would be happy to contribute & add the remaining Atmospheric Model 😄