Made numba as mandatory in README.md
poliastro/poliastro pull request #1147
Opened 2021-04-01 14:29 UTC by AlphaVictorDelta

Solved Issue #1146. 

This is my first open-source contribution ever.

2021-04-01 15:46 UTC, Yash-10 commented
Hello @AlphaVictorDelta thank you for this pull request and congratulations for your first open-source contribution.

I was thinking of this as a rather simple change by just removing "optional" for numba instead of writing "mandatory" since all the requirements are infact mandatory. I have also changed the issue title to better address it.

Also there are some CI failures (similar as in #1132) which we will have to deal with separately.

If you have any questions, please feel free to ask!

2021-04-01 15:55 UTC, AlphaVictorDelta commented
@Yash-10 so should I delete this pull request and make another pull request?

2021-04-01 16:05 UTC, Yash-10 commented
@AlphaVictorDelta No need to delete this pull request. You can make the changes in this PR itself :)

2021-04-02 06:48 UTC, DhruvSondhi requested changes
Please take a look at the requested changes :)

2021-04-02 06:48 UTC, DhruvSondhi commented on README.md
> +|    Name:     | poliastro                                                                                                                                    |
Hello @AlphaVictorDelta ... I don't think this needs to be changed as it is already configured correctly ... Can you please revert this back?

2021-04-02 06:48 UTC, DhruvSondhi commented on README.md
> +_Grazie mille!_
Also, this can be reverted back ... GitHub works correctly with normal Markdown syntax :)

2021-04-03 01:55 UTC, AlphaVictorDelta commented
@DhruvSondhi  Done!

2021-04-03 03:02 UTC, DhruvSondhi commented
Hey @AlphaVictorDelta, I am not able to see the changes 🤔 ... Have you pushed the commits? & Please Squash all the commits as they are just solving a small issue :)

2021-04-03 03:03 UTC, DhruvSondhi commented on README.md
> +_Grazie mille!_
Same here !!

2021-04-03 03:03 UTC, DhruvSondhi commented on README.md
> +|    Name:     | poliastro                                                                                                                                    |
No changes can be seen 🤔

2021-04-03 03:05 UTC, closed without merging