Fix validation trigger
poliastro/poliastro pull request #1176
Opened 2021-04-16 17:21 UTC by jorgepiloto

Yet another try to fix the validation trigger, hope this to be the last one 🤞🏽

2021-04-17 10:01 UTC, astrojuanlu requested changes
It's weird that this still doesn't work 🤔 We would need to find a way so that, if the POST request fails, the workflow fails.

2021-04-17 10:01 UTC, astrojuanlu commented on .github/workflows/validation_trigger.yml
> +          -H "Content-Type: application/json" https://api.github.com/repos/poliastro/validation/actions/workflows/ci_actions/dispatches \
I think this is the correct workflow: https://api.github.com/repos/poliastro/validation/actions/workflows/ci_actions.yml

2021-04-17 16:46 UTC, jorgepiloto commented
This is working through command line but not sure why it fails if triggered from here... 🤔

2021-04-17 17:48 UTC, astrojuanlu commented on .github/workflows/validation_trigger.yml
> -    environment: validation-env
Shouldn't we keep this? Perhaps if we remove the line, the env vars are not properly read

2021-04-18 09:23 UTC, astrojuanlu commented
Idea: use RequestBin or similar services to understand if the `POST` request is being performed correctly. On it.

2021-04-18 09:37 UTC, astrojuanlu commented
@jorgepiloto Authorization headers are empty.

2021-04-18 09:47 UTC, astrojuanlu commented on .github/workflows/validation_trigger.yml
> +          -XPOST -u "${{ secrets.VALIDATION_USER }}:${{ secrets.VALIDATION_PASS }}" \
I think this syntax just doesn't work: https://docs.github.com/en/actions/reference/encrypted-secrets#example-using-bash let me try something different

2021-04-18 10:01 UTC, astrojuanlu commented
> Secrets are not passed to workflows that are triggered by a pull request from a fork.

![Screenshot_2021-04-18 Build software better, together](https://user-images.githubusercontent.com/316517/115141655-d449fd00-a03d-11eb-9281-ea835241c648.png)

I think this is it @jorgepiloto. We should find another way to trigger this, I think.

2021-04-18 10:22 UTC, astrojuanlu requested changes
After reading https://blog.teddykatz.com/2021/03/17/github-actions-write-access.html, it makes a lot of sense that secrets are not available for pull request, since an attacker could send a malicious pull request and print them.

I am not sure how was this working before, perhaps they changed something. As the action was not failing when an error message is returned, I am not sure when this change happened.

@jorgepiloto although it's very attractive to know whether a pull request passed the validation, I don't think this is possible with our current structure. Given that the token must have `actions:write` permissions on the `repo` token, it's just dangerous to make it public.

I only see these solutions:

- Bring everything into the same repository. I don't think it's very practical, we could discuss it again as a last resort.
- Create our own bot or action that does this properly on pull requests. A lot of work.
- Assume that we will only trigger validations from `main`, and keep an eye on it especially when a release approaches. I think this is the simplest solution for now.

Therefore, we need to make these changes:

- Make the action fail if curl (✔️  done)
- Rework the CI so these triggers are only sent from `main`, where the environment secrets are available, so we avoid getting failures for every pull request
- Squash all the commits into one

2021-04-18 15:46 UTC, jorgepiloto commented
Closing this in favor of #1179. For future modifications and maintenance, it is important to remember that this must be done through branches which belong to the repository, not by ones which belong to forks.

2021-04-18 15:46 UTC, closed without merging