Move earth sensor computations to core
poliastro/poliastro pull request #1191
Opened 2021-05-01 08:06 UTC by Yash-10

This PR tries to move computations related to earth sensors to `core`. 

Additionally, the conversion of variable names (in the extended ascii format) to printable ascii characters have been made for consistency.

Thanks!!

2021-05-03 09:41 UTC, Yash-10 commented
@astrojuanlu I think #1196 could get resolved here. Could you have a look?

The codecov/patch test didn't execute for some reason. I am trying to figure out the reason for this..

Thanks!

2021-05-03 09:54 UTC, astrojuanlu commented
Indeed, #1196 got solved here! Do you know if it's just the whitespace or something else?

2021-05-03 10:07 UTC, Yash-10 commented
> Do you know if it's just the whitespace or something else?

I think it would not have to do with whitespace issues. I would try to find the reason behind this :)

2021-05-03 10:12 UTC, astrojuanlu commented
I opened #1199 to discuss about variable names. But I'm +0 (meaning: not totally convinced, but slightly positive) on this change.

2021-05-03 10:17 UTC, astrojuanlu requested changes
Left some comments, but apart from that, this looks good to me!

This is on the verge of not being merged though, since I am preparing the beta release now. So if we could make a smaller PR just fixing the docstring issues, that would be great.

2021-05-03 10:17 UTC, astrojuanlu commented on src/poliastro/earth/sensors.py
> +@u.quantity_input(h=u.km, n_fov=u.rad, n_center=u.rad, R=u.km)
If we're doing this, let's not rename `η` to `n`, and use `eta` instead.

```suggestion
@u.quantity_input(h=u.km, eta_fov=u.rad, eta_center=u.rad, R=u.km)
```

(this applies everywhere)

2021-05-03 10:17 UTC, astrojuanlu commented on src/poliastro/earth/sensors.py
> +    lambda_min: ~astropy.units.Quantity
For some reason, `~astropy.units.Quantity` does not always work:

![Screenshot_2021-05-03 poliastro earth sensors — poliastro 0 15 dev0 documentation(1)](https://user-images.githubusercontent.com/316517/116865062-36435e80-ac09-11eb-8113-434f8950d420.png)

2021-05-03 10:17 UTC, astrojuanlu commented on src/poliastro/earth/sensors.py
> +        This formula always gives the answer for the short way to the target ot the acute angle, beta,
Why?

2021-05-03 10:17 UTC, astrojuanlu commented on tests/tests_earth/test_sensors.py
> +    assert "beta must be between 0º and 180º" in excinfo.exconly()
+1 on being consistent between variable names and error messages.

2021-05-03 11:45 UTC, Yash-10 commented
> This is on the verge of not being merged though, since I am preparing the beta release now.

Thanks for the suggestions, I would make the required changes and we shall look at it after the release!

2021-05-16 15:32 UTC, astrojuanlu requested changes
Thanks again for this @Yash-10 ! I have recently renamed one of the functions, could you please rebase this on top of current `main`?

2021-05-16 15:56 UTC, Yash-10 commented
Sorry @astrojuanlu for not keeping this branch up to date. While I rebase, could you let me know from the discussions in #1199, whether we have decided to keep the variable names as they are in current `main` or the one I had changed?

Thanks!

2021-05-24 06:29 UTC, Yash-10 commented
Since it was decided to use ascii variable names at the high-level and allow using non-ascii at the low level, I have tried to change it accordingly.

The `codeclimate` failure seems a bit tricky. It says `ground_range_diff_at_azimuth` has 10 arguments but infact it has only 7 arguments. I wonder if it has something to do with the function being both jitted and uses non-ascii variables?

2021-05-25 05:39 UTC, astrojuanlu commented
@Yash-10 sorry, don't pay much attention to CodeClimate, we are not strict about it (in fact, we look at it very rarely). You can revert your last commit it you want, I'll look at your PR soon.

2021-05-25 05:53 UTC, Yash-10 commented
Thanks @astrojuanlu I reverted the recent commit.

It was interesting to note that changing variable names to ascii in core had removed the codeclimate issues. If there is a need, we could probably think of configuring `codeclimate.yml` to ignore such issues if non-ascii variables are used in core anywhere..

2021-06-11 08:38 UTC, astrojuanlu commented
@Yash-10 could you please rebase this one on top of `main` after we merge #1191? :)

2021-06-11 08:40 UTC, astrojuanlu approved these changes
This is good to go!

2021-06-11 10:18 UTC, merged

2021-06-11 10:25 UTC, astrojuanlu commented
Automerge worked! Nice 😎

2021-06-11 10:29 UTC, Yash-10 commented
Its really great! Thanks for merging!