Modification units poliastro_plotting_core.py
poliastro/poliastro pull request #1318
Opened 2021-09-09 17:33 UTC by JohaMR

fix #1291

2021-09-09 18:28 UTC, astrojuanlu reviewed
Congratulations for your first pull request 🎉 

All the tests have passed, which means that nothing broke 👍🏼

Only the quality check failed, because there are some whitespace things to change. No rush.

Before we continue, we are going to try to see if this solves your original request. I will give you more instructions soon.

2021-09-10 07:27 UTC, astrojuanlu commented
@JohaMR To see if this solves your original request, can you please install this version of poliastro:

```
pip install https://github.com/JohaMR/poliastro/archive/refs/heads/patch-1.zip
```

and see if you can now change the units of your plot?

```python
from astropy import units as u
from astropy.time import Time
from poliastro.twobody import Orbit
from poliastro.plotting import OrbitPlotter3D

ceres = Orbit.from_sbdb("510466")
epoch = Time("2021-05-30 14:10:00", scale="tdb")
ceres_may = ceres.propagate(epoch)
ceres_may.epoch.iso
frame = OrbitPlotter3D(unit=u.au)  # <-------------------------
frame.plot(ceres_may, label="510466")
frame.show()
```

? If it works, we can address the whitespace changes and merge this 🚀

2021-09-10 20:15 UTC, JohaMR commented
> @JohaMR Para ver si esto resuelve su solicitud original, puede instalar esta versión de poliastro:
> 
> ```
> pip install https://github.com/JohaMR/poliastro/archive/refs/heads/patch-1.zip
> ```
> 
> y vea si ahora puede cambiar las unidades de su parcela?
> 
> ```python
> de  unidades de importación de astropía  como u de astropía . time import Time from poliastro . importación de dos cuerpos Orbit de poliastro . trazado de importación OrbitPlotter3D ceres = Orbit . from_sbdb ( "510466" )
>  epoch = Time ( "2021-05-30 14:10:00" , scale = "tdb" )
>  ceres_may = ceres . Propagar (   
>    
>    
>    
> 
>       época )
>  ceres_may . época . marco iso 
> = OrbitPlotter3D ( unidad = u . au )   # <------------------------- marco . trama ( ceres_may , label = "510466" )
>  marco . mostrar ()  
> ```
> 
> ? Si funciona, podemos abordar los cambios de espacios en blanco y fusionar esto🚀

2021-09-10 20:16 UTC, JohaMR commented
I did what you suggest and it didn't work

2021-09-10 21:11 UTC, astrojuanlu commented
Thanks! No need to close the pull request, we can keep making changes

2021-09-11 10:40 UTC, astrojuanlu commented
There's at least a couple more things we have to change:

https://github.com/poliastro/poliastro/blob/48c854a4ad5500116f7c09ca171f77a60e2de04b/src/poliastro/plotting/core.py#L152-L155

https://github.com/poliastro/poliastro/blob/48c854a4ad5500116f7c09ca171f77a60e2de04b/src/poliastro/plotting/core.py#L251-L254

Instead of the string `"(km)"`, we should use `f"({self._unit})".

_Still_, the unit seems to have no effect on the values, and I don't understand why. I will keep investigating.

2021-09-11 10:42 UTC, astrojuanlu commented
There are more parts of the plotting code that default to kilometers. This is more complicated than I thought 😃 But we'll do it!

2021-09-13 15:15 UTC, astrojuanlu commented
@JohaMR could you:

1. Make the edits I suggested in https://github.com/poliastro/poliastro/pull/1318#issuecomment-917384373
2. Add `unit=unit` in the `super().__init__` calls of `OrbitPlotter3D` and `OrbitPlotter2D`,
3. Repeat `pip install https://github.com/JohaMR/poliastro/archive/refs/heads/patch-1.zip`, and
4. Check if now the units are shown?

2021-09-13 19:41 UTC, astrojuanlu requested changes

2021-09-13 19:41 UTC, astrojuanlu commented on src/poliastro/plotting/core.py
> +                xaxis=dict(title="x f"({self._unit})""),
This is a syntax error, it should be:

```suggestion
                xaxis=dict(title=f"x ({self._unit})"),
```

and so forth

2021-09-13 20:08 UTC, astrojuanlu commented
First checkbox done ✅  missing the other 3 :)

2021-09-13 21:09 UTC, JohaMR commented
correct code, now it is possible to change units 🎉

2021-09-13 21:18 UTC, astrojuanlu approved these changes
Congratulations! 🎉 

I just made some whitespace fixes to your pull request, and as soon as the Continuous Integration checks pass, we will merge it.

2021-09-13 21:59 UTC, merged