Added `gabbard.py` in `poliastro.plotting`
poliastro/poliastro pull request #1464
Opened 2022-02-04 08:50 UTC by TheBuffer

Tried adding a Static Gabbard Plotter as described in #1431
and tested it out with the COSMOS 1408 DEB data
![Screenshot from 2022-02-04 14-12-07](https://user-images.githubusercontent.com/62299190/152498954-80be9d83-34c1-49b8-8687-95ee8a5ef4a8.png)

2022-02-04 10:16 UTC, astrojuanlu reviewed
Thanks @TheBuffer for this contribution! 🎉 I rebased your branch and everything looks good initially. I'm going to review this in depth in a few hours.

2022-02-07 08:54 UTC, TheBuffer commented
Should I try adding the Dynamic Gabbard Plots and maybe integrating something which takes in the Debris Ephemerides as an input?

2022-02-07 10:40 UTC, astrojuanlu requested changes
This looks very good, thanks @TheBuffer for your contribution! I'd say let's focus on static Gabbard plots for now to make things simpler, we can expand it later.

I left some comments, but most importantly this will need some tests. You can take inspiration from the image tests we have for other plotters, that compare an expected outcome with the actual one:

https://github.com/poliastro/poliastro/tree/main/tests/tests_plotting

2022-02-07 10:40 UTC, astrojuanlu commented on src/poliastro/plotting/gabbard.py
> +    @staticmethod
I'd say we don't need this static method? (See my comment below)

2022-02-07 10:40 UTC, astrojuanlu commented on src/poliastro/plotting/gabbard.py
> +            perigee, apogee, period = self._get_orbit_properties(orbit)
We could simplify this to remove the static method:

```suggestion
            perigee, apogee, period = orbit.r_p, orbit.r_a, orbit.period
```

2022-02-07 10:40 UTC, astrojuanlu commented on src/poliastro/plotting/gabbard.py
> +        self._ax.set_ylabel("Altitude(km)")
```suggestion
        self._ax.set_xlabel("Period (min)")
        self._ax.set_ylabel("Altitude (km)")
```

(see comment about units above)

2022-02-07 10:40 UTC, astrojuanlu commented on src/poliastro/plotting/gabbard.py
> +            periods.append(period.to(u.min).value)
Probably we should not hardcode `u.min` here and make it a parameter, like we did for other plotters in #1318

2022-02-07 10:40 UTC, astrojuanlu commented on src/poliastro/plotting/gabbard.py
> +        """
```suggestion
        """Plots a Static Gabbard Plot given a list of Orbits

        Parameters
        ----------
        orbits : ~poliastro.twobody.orbit.Orbit List
            The Orbits whose perigee and apogee will be plotted.

        """
```

2022-02-09 21:42 UTC, astrojuanlu requested changes
Starting to look good! Left only one comment. With that, I'm 👍🏽 as soon as the tests pass.

2022-02-09 21:42 UTC, astrojuanlu commented on src/poliastro/examples.py
> +debris_orbits_list = []
I'd prefer that we put this only in the tests, rather than shipping it with the library.

2022-02-09 21:48 UTC, astrojuanlu commented
There seem to be some subtle (unimportant) typography differences between the baseline image and the result. I downloaded `result.png` via SSH, it's this:

![result](https://user-images.githubusercontent.com/316517/153295784-2b2217ce-f9dd-483e-bb3e-51468215fc61.png)

and the difference is this:

![result-failed-diff](https://user-images.githubusercontent.com/316517/153295796-ed95e903-5c35-4c3f-8cf2-71487e1eced6.png)

You can probably just download `result.png` and commit it as the baseline.

2022-02-10 11:08 UTC, astrojuanlu approved these changes
Looks good to me! Thanks again @TheBuffer !

2022-02-10 11:08 UTC, merged